services:
  - type: web
    name: full-mern-project-frontend
    buildCommand: cd frontend && chmod +x build.sh && ./build.sh
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://full-mern-project.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
