services:
  - type: web
    name: job-portal-backend
    runtime: node
    buildCommand: ./build.sh
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
