services:
  - type: web
    name: full-mern-project-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://full-mern-project.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
